version: '3.8'

networks:
  devops_project:
    driver: bridge

volumes:
  database:


services:

  database:
    environment:
      - MYSQ_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    image: mysql:5.7
    networks:
      - devops_project
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  backend:
    depends_on:
      - database
    image: droidzed/aymendhahri-5sim3-g1-projet4-spring-angular:latest
    networks:
      - devops_project
    container_name: backend-spring
    ports:
      - "8082:8082"

  frontend:
    depends_on:
      - database
      - backend
    image: droidzed/aymendhahri-5sim3-g1-projet4-spring-angular-front:latest
    ports:
      - "4200:80"
    networks:
      - devops_project
    container_name: frontend-angular
