version: '3.8'

services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - devops-network
  spring:
    container_name: spring
    depends_on:
      - db
    image: yassinemessaoud/medyassinemessaoud-5sim3-g1-projet4-spring-angular:1.0.0
    ports:
      - "8082:8082"
    networks:
      - devops-network
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  devops-network:
    driver: bridge