FROM adoptopenjdk/openjdk11:x86_64-ubuntu-jre-11.0.21_9
EXPOSE 8082
ADD target/5SIM3-G1-Projet4-Spring-Angular.jar /5SIM3-G1-Projet4-Spring-Angular.jar
ENTRYPOINT ["java","-jar","/5SIM3-G1-Projet4-Spring-Angular.jar"]