FROM eclipse-temurin:11-jdk-alpine

ADD /target/5SIM3-G1-Projet4-Spring-Angular.jar /5SIM3-G1-Projet4-Spring-Angular.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/5SIM3-G1-Projet4-Spring-Angular.jar"]